### ISSUE TITLE
Error: You are accessing the Scene#data object which is no longer used.

### ISSUE THREAD

**Issue by skepickle** [skepickle/foundryvtt-gaming-table-player#8]
the Scene DataModel changed, and the module needs to access the _id value directly:
```
Error: You are accessing the Scene#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at Scene._logV10CompatibilityWarning (commons.js:6617:14)
    at get data [as data] (commons.js:6517:24)
    at GamingTablePlayer.pullFocus (gaming-table-player.js:107:47)
    at keyDown (gaming-table-player.js:122:21)
logCompatibilityWarning @ commons.js:1703
_logV10CompatibilityWarning @ commons.js:6617
get data @ commons.js:6517
pullFocus @ gaming-table-player.js:107
keyDown @ gaming-table-player.js:122
foundry.js:676
```
Basically "game.scenes.viewed.data._id" needs to be changed to "game.scenes.viewed._id"

**Comment by skepickle** [comment]
Bug should be resolved by v1.0.1
